title: Default Page

columns:
  main:
    width: 2/3
    fields:
      headline:
        label: Headline
        type: writer
        nodes:
          - heading
          - paragraph
        headings:
          - 2
        marks: false
  sidebar:
    width: 1/3
    fields:
      featured_image:
        label: Featured Image
        type: files
        multiple: false
        uploads: image
        layout: cards
