title: Default Page

columns:
  main:
    width: 2/3
    sections:
      header:
        type: fields
        fields:
          headline:
            label: Headline
            type: writer
            nodes:
              - heading
              - paragraph
            headings:
              - 2
            marks: false
  sidebar:
    width: 1/3
    sections:
      hero:
        type: fields
        fields:
          hero_image:
            label: Hero Image
            type: files
            multiple: false
            uploads: image
            layout: cards