title: Default Page

columns:
  main:
    width: 2/3
    fields:
      text:
        label: Text
        type: textarea
        size: huge
  sidebar:
    width: 1/3
    fields:
      pages:
        type: pages
        template: default
      files:
        label: Featured Image
        type: files
        multiple: false
        template: default
        uploads: image