title: Site

tabs:
  content:
    label: Content
    icon: text
    columns:
      main:
        width: 2/3
        sections:
          pages:
            type: pages
            width: 1/2
            layout: cards
      sidebar:
        width: 1/3
        fields:
          menu:
            label: Hauptmenu
            type: pages
  settings:
    label: Settings
    icon: settings
    fields: